theme: jekyll-theme-minimal
title: Alessandro Borghi
logo: "DSC00627.jpg"
description: 
[CV](CV_Summ.pdf) 
<br><br>
[LinkedIn](http://linkedin.com/in/alessandro-borghi-736ab9b4)  
<br><br> 
[Twitter](https://twitter.com/alleborghi1996)
