theme: jekyll-theme-minimal
#remote_theme: benbalter/retlab
#remote_theme: epidrome/cover-card
title: Alessandro Borghi
logo: "IMG-3622-1.jpg"
description: <a href="CV_short.pdf">CV </a> <br>
    <a href="http://linkedin.com/in/alessandro-borghi-736ab9b4">LinkedIn </a>
    <br>
    <a href="https://scholar.google.com/citations?user=VBdW03cAAAAJ&hl=en&oi=sra">google scholar </a>
    <br>
    <a [lastname]{at}tu-berlin.de > </a>
