theme: jekyll-theme-minimal
title: Alessandro Borghi
logo: "DSC00627.jpg"
description: [CV](CV_Summ.pdf) <br>
    <a href="http://linkedin.com/in/alessandro-borghi-736ab9b4">LinkedIn </a>
    <br>
    <a href="https://twitter.com/alleborghi1996">Twitter </a>
