theme: jekyll-theme-minimal
title: Alessandro Borghi
logo: "DSC00627.jpg"
description: 
- <a href="http://linkedin.com/in/alessandro-borghi-736ab9b4">LinkedIn </a>
- <a href="https://twitter.com/alleborghi1996">Twitter </a>
<!-- [Twitter](https://twitter.com/alleborghi1996)-->
