theme: jekyll-theme-minimal
title: Alessandro Borghi
logo: "DSC00627.jpg"
description: 
- [CV](CV_Summ.pdf)
- [LinkedIn](http://linkedin.com/in/alessandro-borghi-736ab9b4) 
- [Twitter](https://twitter.com/alleborghi1996)
