theme: jekyll-theme-minimal
#remote_theme: benbalter/retlab
#remote_theme: epidrome/cover-card
title: Alessandro Borghi
logo: "DSC00627.jpg"
description: <a href="CV_Summ.pdf">CV </a> <br>
    <a href="http://linkedin.com/in/alessandro-borghi-736ab9b4">LinkedIn </a>
    <br>
    <a href="https://twitter.com/alleborghi1996">Twitter </a>
